LOG_FILE: "log/eth_block_data.log"

# Centrifugo
centrifugo_url: "ws://localhost:8000/connection/websocket"
centrifugo_channel: "news"

# Kafka / Redpanda
kafka_broker: "localhost:9093"
kafka_topic: "latency-test-topic"
kafka_group_id: "centrifugo-pusher"
