LOG_FILE: "log/dev.log"

# Centrifugo
centrifugo_url: "ws://localhost:8000/connection/websocket"
centrifugo_channel: "news:updates"

# Kafka / Redpanda
kafka_broker: "localhost:9093"
kafka_topic: "orders"
kafka_group_id: "matching_engine_group"
