log_file: "log/dev.log"

centrifugo:
  url: "ws://localhost:8000/connection/websocket"
  channel: "news:updates"

kafka:
  broker: "localhost:9093"
  topics:
    orders: "validated_orders"
    trades: "trade.history"
  group_id: "matching_engine_group_debug_001"
  linger_ms: 0
  socket_keepalive_enable: true

scylladb:
  hosts:
    - "127.0.0.1:9042"
  keyspace: "trading"
  replication_factor: 1
  connection_timeout_ms: 5000
  request_timeout_ms: 3000
