log_file: "log/dev.log"

centrifugo:
  url: "ws://localhost:8000/connection/websocket"
  channel: "news:updates"

kafka:
  broker: "localhost:9093"
  topic: "orders"
  group_id: "matching_engine_group"
