log_file: "log/prod.log"

centrifugo:
  url: "ws://prod-centrifugo:8000/connection/websocket"
  channel: "news:updates"

kafka:
  broker: "prod-redpanda:9093"
  topic: "orders"
  group_id: "matching_engine_group_prod"
